[default]
name = "integer"
weight_width = 8
weight_frac_width = 3
data_in_width = 8
data_in_frac_width = 5
bias_width = 8
bias_frac_width = 5

[module_classes_to_modify.conv1d]
name = "default"

[module_classes_to_modify.conv2d]
name = "default"

[module_classes_to_modify.linear]
name = "default"

[module_classes_to_modify.relu]
name = "default"

[functions_to_modify.add]
name = "default"

[functions_to_modify.bmm]
name = "default"

[functions_to_modify.matmul]
name = "default"

[functions_to_modify.relu]
name = "default"

[methods_to_modify.add]
name = "default"

[methods_to_modify.bmm]
name = "default"

[methods_to_modify.matmul]
name = "default"

[methods_to_modify.relu]
name = "default"

[modules_to_modify.conv1]
name = "default"

[modules_to_modify.bn1]
name = "default"

[modules_to_modify.relu]
name = "default"

[modules_to_modify.maxpool]
name = "default"

[modules_to_modify."layer1.0.conv1"]
name = "default"

[modules_to_modify."layer1.0.bn1"]
name = "default"

[modules_to_modify."layer1.0.relu"]
name = "default"

[modules_to_modify."layer1.0.conv2"]
name = "default"

[modules_to_modify."layer1.0.bn2"]
name = "default"

[modules_to_modify."layer1.1.conv1"]
name = "default"

[modules_to_modify."layer1.1.bn1"]
name = "default"

[modules_to_modify."layer1.1.relu"]
name = "default"

[modules_to_modify."layer1.1.conv2"]
name = "default"

[modules_to_modify."layer1.1.bn2"]
name = "default"

[modules_to_modify."layer2.0.conv1"]
name = "default"

[modules_to_modify."layer2.0.bn1"]
name = "default"

[modules_to_modify."layer2.0.relu"]
name = "default"

[modules_to_modify."layer2.0.conv2"]
name = "default"

[modules_to_modify."layer2.0.bn2"]
name = "default"

[modules_to_modify."layer2.0.downsample.0"]
name = "default"

[modules_to_modify."layer2.0.downsample.1"]
name = "default"

[modules_to_modify."layer2.1.conv1"]
name = "default"

[modules_to_modify."layer2.1.bn1"]
name = "default"

[modules_to_modify."layer2.1.relu"]
name = "default"

[modules_to_modify."layer2.1.conv2"]
name = "default"

[modules_to_modify."layer2.1.bn2"]
name = "default"

[modules_to_modify."layer3.0.conv1"]
name = "default"

[modules_to_modify."layer3.0.bn1"]
name = "default"

[modules_to_modify."layer3.0.relu"]
name = "default"

[modules_to_modify."layer3.0.conv2"]
name = "default"

[modules_to_modify."layer3.0.bn2"]
name = "default"

[modules_to_modify."layer3.0.downsample.0"]
name = "default"

[modules_to_modify."layer3.0.downsample.1"]
name = "default"

[modules_to_modify."layer3.1.conv1"]
name = "default"

[modules_to_modify."layer3.1.bn1"]
name = "default"

[modules_to_modify."layer3.1.relu"]
name = "default"

[modules_to_modify."layer3.1.conv2"]
name = "default"

[modules_to_modify."layer3.1.bn2"]
name = "default"

[modules_to_modify."layer4.0.conv1"]
name = "default"

[modules_to_modify."layer4.0.bn1"]
name = "default"

[modules_to_modify."layer4.0.relu"]
name = "default"

[modules_to_modify."layer4.0.conv2"]
name = "default"

[modules_to_modify."layer4.0.bn2"]
name = "default"

[modules_to_modify."layer4.0.downsample.0"]
name = "default"

[modules_to_modify."layer4.0.downsample.1"]
name = "default"

[modules_to_modify."layer4.1.conv1"]
name = "default"

[modules_to_modify."layer4.1.bn1"]
name = "default"

[modules_to_modify."layer4.1.relu"]
name = "default"

[modules_to_modify."layer4.1.conv2"]
name = "default"

[modules_to_modify."layer4.1.bn2"]
name = "default"

[modules_to_modify.avgpool]
name = "default"

[modules_to_modify.fc]
name = "default"
