modifiable_layers = ["linear", "relu", "conv2d"]
modifiable_functions = ["relu", "matmul", "bmm", "add"]

[default]
name = "minifloat_simple"
weight_width = 8
weight_exponent_width = 4
weight_exponent_bias = 7
data_in_width = 8
data_in_exponent_width = 4
data_in_exponent_bias = 7
bias_width = 8
bias_exponent_width = 4
bias_exponent_bias = 7
